name : Python CI

on:
  push:
    branch: [main]
  pull_request:
    branch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      -uses: actions/checkout@v4

      -name: set up python
       uses: actions/setup-python@v5
       with:
        python-version: '3.10'
        cache: 'pip'

      -name: dependencies
       run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      -name: Run tests
       run: pytest
      
